name: Continous integration tests

on:
  push:
  pull_request:

jobs:
  ci_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        cxx-compiler: [g++-9, g++-10, clang++-10, clang++-11]

    steps:
      - uses: actions/checkout@v2

      - name: configure
        run: >
          cmake
          -S .
          -B build
          -DNDARRAY_TESTS=ON
          -DCMAKE_INSTALL_PREFIX=/tmp/ndarray
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx-compiler }}

      - name: build
        run: cmake --build build
      - name: run tests
        run: ctest
        working-directory: ./build/tests
